services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
  web:
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - .:/my_chatGPT
    ports:
      - "3000:3000"
    depends_on:
      - db
  # redis:
  #   image: redis:3.2-alpine
  #   command: redis-server --port 7479
  #   ports:
  #     - "7479:7479"

  # sidekiq:
  #   build: .
  #   command: bundle exec sidekiq
  #   depends_on:
  #     - db
  #     - redis
  #   env_file:
  #     - .env