
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: db
  username: postgres
  password: password
  port: 5432

development:
  <<: *default
  database: my_chatGPT_development

test:
  <<: *default
  database: my_chatGPT_test

production:
  <<: *default
  database: my_chatGPT_production
  username: my_chatGPT
  password: <%= ENV["MY_CHATGPT_DATABASE_PASSWORD"] %>
